version: "3"

services:
    jenkins:
        image: jenkins/jenkins:lts
        container_name: jenkins
        ports:
            - "8080:8080"
            - "50000:50000"
        volumes:
            - jenkins_home:/var/jenkins_home
            - /e/sem3/Devops/devops4:/var/jenkins_home/devops4
        environment:
            JENKINS_OPTS: --httpPort=8080
            JAVA_OPTS: "-Dhudson.plugins.git.GitSCM.ALLOW_LOCAL_CHECKOUT=true"
        networks:
            - sonar-network

    sonarqube:
        image: sonarqube:latest
        container_name: sonarqube
        depends_on:
            - sonar_db
        environment:
            SONAR_JDBC_URL: jdbc:postgresql://sonar_db:5432/sonar
            SONAR_JDBC_USERNAME: sonar
            SONAR_JDBC_PASSWORD: sonar
            SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: "true"
        ports:
            - "9000:9000"
        volumes:
            - sonarqube_conf:/opt/sonarqube/conf:rw
            - sonarqube_data:/opt/sonarqube/data:rw
            - sonarqube_extensions:/opt/sonarqube/extensions:rw
            - sonarqube_logs:/opt/sonarqube/logs:rw
            - sonarqube_temp:/opt/sonarqube/temp:rw
        networks:
            - sonar-network

    sonar_db:
        image: postgres:latest
        container_name: sonarqube_db
        environment:
            POSTGRES_USER: sonar
            POSTGRES_PASSWORD: sonar
            POSTGRES_DB: sonar
        volumes:
            - sonar_db:/var/lib/postgresql
            - sonar_db_data:/var/lib/postgresql/data
        networks:
            - sonar-network

    nexus:
        image: sonatype/nexus3:latest
        container_name: nexus
        ports:
            - "8081:8081"
        volumes:
            - nexus-data:/nexus-data
        networks:
            - sonar-network

volumes:
    jenkins_home:
    nexus-data:
    sonarqube_conf:
    sonarqube_data:
    sonarqube_extensions:
    sonarqube_logs:
    sonarqube_temp:
    sonar_db:
    sonar_db_data:

networks:
    sonar-network:
        driver: bridge